### ISSUE TITLE
Making our own style 💇‍♀️

### ISSUE THREAD

**Issue by lauraporta** [neuroinformatics-unit/troubleshooting#9]
Some ideas on improvements to do:
- Add our logo
- Use the same colour palette of the logo?
- The search could show the few lines of the paragraph the word is found in

**Comment by niksirbi** [comment]
I propose cloning [PyData Sphinx Theme](https://github.com/pydata/pydata-sphinx-theme) in our organization (we can call it `neuroinformatics-sphinx-theme`). We can then make any style changes there and use that theme for all our sphinx builds.
